### ISSUE TITLE
在windows server 2022系统运行提示Your operating systern is not supported. 

### ISSUE THREAD

**Issue by pkr5277** [CheshireCC/fatser-whisper-GUI#1]
在windows server 2022系统运行提示Your operating systern is not supported.

**Comment by CheshireCC** [comment]
> 在windows server 2022系统运行提示Your operating systern is not supported.

由于应用程序相关功能未在 windows server 上进行过测试，所以发布时安装包锁闭了相关系统，后续可能会有测试计划。

**Comment by CheshireCC** [comment]
@pkr5277 0.2.2 暂时先支持在 windows server 2022、2019、2016 上安装 但未进行太多测试
