### ISSUE TITLE
视频中间有1-2分钟无声，或者声音很小的时候，无法正常输出内容

### ISSUE THREAD

**Issue by iXi101** [CheshireCC/fatser-whisper-GUI#11]
在处理一段视频的时候，视频中间有无声片段，或者声音很小，可能持续 1-2 分钟，后续的视频有说话了，但是无法正常识别，输出内容，这个时候，我可以修改什么参数来调节

**Comment by iXi101** [comment]
经历了 8 个小时左右，44个 版本多小时的文件，突然不工作了，这个语音文件，他可以成功一个提取一个吗？

**Comment by CheshireCC** [comment]
> 在处理一段视频的时候，视频中间有无声片段，或者声音很小，可能持续 1-2 分钟，后续的视频有说话了，但是无法正常识别，输出内容，这个时候，我可以修改什么参数来调节


According to your description, your audio has lost its content. Try the following
- change the VAD `threshold` to a smaller value, such as 0.3 or something less than 0.5
- `change log_prob_threshold` to a smaller value
- `compression_ratio_threshold` is changed to a larger value
- `no_speech_threshold` is changed to a larger value
- close `condition_on_previous_text`

You can try some of the above, or at the same time. It is recommended that you try the VAD option and set `condition_on_previous_text` to `False` first.
If your audio content is long, you can use the cutting tool to cut out a few minutes (for example, 5 minutes), and try the parameters for the clips that are easy to fail.

In addition, for less clear audio content of poor quality, you can try to use enhancement tools to enhance the human voice, and then use the enhanced audio for speech recognition, which will be very helpful.

**Comment by CheshireCC** [comment]
> 经历了 8 个小时左右，44个 版本多小时的文件，突然不工作了，这个语音文件，他可以成功一个提取一个吗？

I am not very clear about your description. It seems that your translation tool is not very good. Thank you for using Chinese to talk to me. Why don't we speak English?

**Comment by iXi101** [comment]
> > 经历了 8 个小时左右，44个 版本多小时的文件，突然不工作了，这个语音文件，他可以成功一个提取一个吗？
> 
> I am not very clear about your description. It seems that your translation tool is not very good. Thank you for using Chinese to talk to me. Why don't we speak English?我不太清楚你的描述。看来你的翻译工具不是很好。谢谢你用中文和我说话。我们为什么不会说英语？

What I mean is, if a file is successful, output a file.
Because I had been using it for about 8 hours, and suddenly it stopped working.

**Comment by CheshireCC** [comment]
> > I am not very clear about your description. It seems that your translation tool is not very good. Thank you for using Chinese to talk to me. Why don't we speak English?我不太清楚你的描述。看来你的翻译工具不是很好。谢谢你用中文和我说话。我们为什么不会说英语？
> 
> What I mean is, if a file is successful, output a file. Because I had been using it for about 8 hours, and suddenly it stopped working.
> 
> 我说呢，原来字打错了，中文挺好的

看来你同时处理了很多个文件，这个问题当处理多个音视频文件的时候确实比较突出。
也许后续版本中可以对字幕文件的输出进行改进，
因为现在使用 whisperX 进行一些后处理工作，我不太想把它作为可选项，而是想把它作为可选步骤，
所以也许我们需要的是一个批处理的工作流，这样既可以满足单个文件的分步骤处理，也可以满足多文件的统一处理

**Comment by iXi101** [comment]
> 看来你同时处理了很多个文件，这个问题当处理多个音视频文件的时候确实比较突出。 也许后续版本中可以对字幕文件的输出进行改进， 因为现在使用 whisperX 进行一些后处理工作，我不太想把它作为可选项，而是想把它作为可选步骤， 所以也许我们需要的是一个批处理的工作流，这样既可以满足单个文件的分步骤处理，也可以满足多文件的统一处理

好的，有个小建议，比如我 everything 搜索出多个想处理的视频或音频，有多个不同路径，我全选，可以直接把搜索出的结果，可以直接拖进去，而不用我一个一个进行添加。

另外你建议用那个模型？

**Comment by CheshireCC** [comment]
> > 看来你同时处理了很多个文件，这个问题当处理多个音视频文件的时候确实比较突出。 也许后续版本中可以对字幕文件的输出进行改进， 因为现在使用 whisperX 进行一些后处理工作，我不太想把它作为可选项，而是想把它作为可选步骤， 所以也许我们需要的是一个批处理的工作流，这样既可以满足单个文件的分步骤处理，也可以满足多文件的统一处理
> 
> 好的，有个小建议，比如我 everything 搜索出多个想处理的视频或音频，有多个不同路径，我全选，可以直接把搜索出的结果，可以直接拖进去，而不用我一个一个进行添加。
> 
> 另外你建议用那个模型？

1. 如果你的显存 大于 8GB 你可以使用任意模型，如果你的显存小于 8GB 你可以使用 largev2 但是计算精度使用 int8 ，当然加载 float32 的模型，但使用 int8 作为计算精度也是可行的，只是加载模型将会耗费更多时间，
2. 目前已经得知，当显存剩余不太多，比如使用 largeV2 模型进行转写之后，已经占用 7.8 GB 显存（假设总共8GB），此时执行后续操作比如 `whisperX时间戳对齐` 功能时将会运转缓慢（这和内存不够时软件运行卡顿同理）。
3. 关于文件拖放，这个功能我只是在犹豫而已，我确实一直考虑制作相关功能。我其实已经进行了一些相关功能的实现，但目前还在进行测试和修改，由于某些原因，它可能在某些情况下不工作。我需要找到一种保持代码实现的简洁和功能性完整之间平衡的方法。

**Comment by iXi101** [comment]
> > 好的，有个小建议，比如我 everything 搜索出多个想处理的视频或音频，有多个不同路径，我全选，可以直接把搜索出的结果，可以直接拖进去，而不用我一个一个进行添加。
> > 另外你建议用那个模型？
> 
> 1. 如果你的显存 大于 8GB 你可以使用任意模型，如果你的显存小于 8GB 你可以使用 largev2 但是计算精度使用 int8 ，当然加载 float32 的模型，但使用 int8 作为计算精度也是可行的，只是加载模型将会耗费更多时间，
> 2. 目前已经得知，当显存剩余不太多，比如使用 largeV2 模型进行转写之后，已经占用 7.8 GB 显存（假设总共8GB），此时执行后续操作比如 `whisperX时间戳对齐` 功能时将会运转缓慢（这和内存不够时软件运行卡顿同理）。
> 3. 关于文件拖放，这个功能我只是在犹豫而已，我确实一直考虑制作相关功能。我其实已经进行了一些相关功能的实现，但目前还在进行测试和修改，由于某些原因，它可能在某些情况下不工作。我需要找到一种保持代码实现的简洁和功能性完整之间平衡的方法。

1.因为真正想问的是，你是基于模型进行调试的，如果你都是一个模型调试，这样我就使用你的参数，可能效果会更好。
2.有没有考虑更换模型，同样的效果，更低的显存占用。
3.比如处理 视频 时，提取 或者 转换 成 音频格式，再进行处理，这样会不会处理更快。

**Comment by CheshireCC** [comment]
模型是使用 OpenAI 的 whisper 模型来进行转写的，目前已经是最节省计算资源的方式了，
参数并不能根据模型或者调试来确定，因为音频数据属于典型的高随机信号，缺乏统计上的稳定性，这是音频数据处理的基本常识，所以参数只能根据不同的数据集来确定，实际上除非有新的小型化本地模型的效果远远超过 OpenAI 的现有方案，否则只能进行尝试以寻找合适的参数，并不存在通用于所有数据的参数
就目前来说，音频转写方案有很多，有的是在线服务的，还有的是收费服务的，比如中国科大讯飞的在线服务，但是这些服务都需要向云端上传数据，并且转写效果上与 whisper 比也只是各有所长。
我比较 Youtube 又或者 其他视频网站的自动字幕，英语语言效果都差不多，但其他语言的效果则参差不齐，有的甚至不如 whisper 这个本地方案，而其他的本地化方案能做到识别 99 种语言还能在 普通民用级显卡上运行起来的基本没有......
关于视频数据处理，实际上现在就是只处理音频数据，如果输入视频数据的话就会自动进行转换，事实上转写时间里会包括转换视频为音频的时间，所以时间会更久。
