### ISSUE TITLE
能否在转写任务完成时生成临时结果文件？

### ISSUE THREAD

**Issue by Creayhhh** [CheshireCC/fatser-whisper-GUI#12]
在进行多任务转写时，在完成一个任务时能否生成一个临时结果文件？
因为在多任务转写，由于意外情况发生（没有转出结果就退出程序、电脑异常崩溃），前面几个转写完成的结果不能保存下来，浪费转写的时间。
所以能否考虑一下添加一个转写完成的临时结果文件的功能？在程序异常退出的时候再次打开程序可以处理上次转写完成的结果。
谢谢！

**Comment by CheshireCC** [comment]
我确实收到这样的反馈，我想的话下一个版本有可能会实现相关功能
