### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by arlovibre** [CheshireCC/fatser-whisper-GUI#13]
Will there be an English language for the GUI? Or is there?

**Comment by arlovibre** [comment]
I see this has English language. Sorry for opening an issue without checking properly, my mistake. Thanks for the work!

**Comment by CheshireCC** [comment]
> I see this has English language. Sorry for opening an issue without checking properly, my mistake. Thanks for the work!

for windows OS， if you don't use Chinese language in system configuration，that will be English language. 
In fact, only Chinese and English are currently supported.
Some English translations may not be good, and you are welcome to discuss the English translation of the interface.
