### ISSUE TITLE
可否添加一个保存修改后参数的功能

### ISSUE THREAD

**Issue by wangao1993** [CheshireCC/fatser-whisper-GUI#14]
可否添加一个保存修改后参数的功能，有时候使用会涉及修改一些参数，但是每次打开软件都要改一次，能不能添加一个保存修改后参数的功能，谢谢！

**Comment by CheshireCC** [comment]
这需要保存读取参数的双操作，添加功能本身不困难但可能设计上需要一些思考，才能使软件使用感觉变得流畅，我可能会在下一个版本进行一些相关尝试

**Comment by CheshireCC** [comment]
新版本以实现该功能
