### ISSUE TITLE
Model error.

### ISSUE THREAD

**Issue by jordan1227** [CheshireCC/fatser-whisper-GUI#16]
Hey, I got a problem. I can't load the model. Can you please tell me what I did wrong?
![32323232](https://github.com/CheshireCC/fatser-whisper-GUI/assets/130075423/3073a65b-a878-4b95-8626-486d83928f80)
![222](https://github.com/CheshireCC/fatser-whisper-GUI/assets/130075423/0623965c-d85e-410d-b724-bca0d37d7894)

**Comment by CheshireCC** [comment]
I'm going to check for this Model, and if this happens again，please check `fasterWhisperGui.log` file for more information

**Comment by CheshireCC** [comment]
I can load this model correctly，you should check `log` file.
And， may be you can try to load model with `cpu`, if that work, you need to make sure that your `GPU` device support CUDA .
Check and update GPU driver program may help you

**Comment by jordan1227** [comment]
Thanks.
