### ISSUE TITLE
Whisperx engine support.

### ISSUE THREAD

**Issue by jkkma** [CheshireCC/fatser-whisper-GUI#2]
Can you add whisperx as engine implementation? With the latest commit they fixed japanese audio giving long segment subtitles, and the subtitle timing is really, really good.
https://github.com/m-bain/whisperX

**Comment by CheshireCC** [comment]
so, The main advantage of WhsiperX is good word-level timestample. I found that WhisperX also use faster-whisper as backend,I think that may be it will be easy to support. But you know that ， time will always be needed for develepment and test.

**Comment by CheshireCC** [comment]
For now, you can try to Adjust VAD parameters just like `max_speech_duration` ,may limit  length of japanese audio subtitles 
 segment.And I'm not sure that WhisperX engine could be embedded in other programs.I need time to learn more about Whsiper and test for it.

**Comment by CheshireCC** [comment]
> Can you add whisperx as engine implementation? With the latest commit they fixed japanese audio giving long segment subtitles, and the subtitle timing is really, really good. https://github.com/m-bain/whisperX

Pre-release version is going to support whisperX!

**Comment by jkkma** [comment]
Nice, looking forward to release version.
