### ISSUE TITLE
批量的时候错误，我选择了两个视频，完成第一个后第二个完成不了

### ISSUE THREAD

**Issue by dadaguai3** [CheshireCC/fatser-whisper-GUI#3]
提示face.
Output...Traceback (most recent call last):File "D: FasterWhisperCUI faster_whisper_CUI transcribe.py", line 386, in runif output format.lower ==all":AttributeError: 'list' object has no attribute ' lower

**Comment by dadaguai3** [comment]
face.
Output...
Traceback (most recent call last):
  File "D:\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 386, in run
    if output_format.lower() == "all":
AttributeError: 'list' object has no attribute 'lower'

**Comment by dadaguai3** [comment]
我使用的是最新版本，上个版本2.3没有问题

**Comment by CheshireCC** [comment]
嗯。。。应该是批量处理的时候 格式参数覆盖的原因，最迟明天将到正式版本

**Comment by CheshireCC** [comment]
批处理问题 0.2.5 版本已经修复

**Comment by dadaguai3** [comment]
> 批处理问题 0.2.5 版本已经修复

这速度太爱了
