### ISSUE TITLE
我在2.3版本遇到一个时间轴问题，

### ISSUE THREAD

**Issue by dadaguai3** [CheshireCC/fatser-whisper-GUI#4]
1
00:00:07,220 --> 00:00:14,410
2
00:00:14,410 --> 00:00:20,450
3
00:00:20,450 --> 00:00:25,010
4
00:00:25,010 --> 00:00:30,210
5
00:00:30,210 --> 00:00:34,510
开始和结尾的时间重叠，1作者他的视频没有这个问题，那么他剩下的所有视频都没有这个问题。2作者他的视频有这个问题，那么剩下的都有重叠问题。
比如以下，说完了too，字幕应该消失，而不是一直显示。
20
00:01:56,740 --> 00:01:59,380
too.
21
00:01:59,380 --> 00:02:04,940
So if you're looking at the eye from the side, this is kind of where the iris is.
我该如何避免这个问题，2.4时间戳对齐可以解决。

**Comment by CheshireCC** [comment]
事实上，时间戳对齐这个问题对于 whisper 来说一直是个大问题，对于更专业的用户 他们一致认为 whisper 的时间轴很差劲。
新版版中启用了 whisperX 引擎支持下的 时间戳对齐功能，但它主要是应用其他 神经网络模型 来处理音频内容，对齐效果取决于该种语言的对应模型，而且并不是每种语言都有预训练的模型，因此并不是所有的语言都得到支持。
实际上，如果用于对质量有较高要求的项目中，可能无论如何无法避免手工检查和校对的工作，此时少量问题可以手动修正字幕文件来保证成果质量，如果未来有更好的解决方案，我可能会继续更新功能到新的版本中。
以上。
