### ISSUE TITLE
新版本启用whisperX对齐以后转录完就停止了，而且也没有输出任何文件，点击取消也没有反应

### ISSUE THREAD

**Issue by wangao1993** [CheshireCC/fatser-whisper-GUI#5]
![屏幕截图 2023-09-28 145740](https://github.com/CheshireCC/fatser-whisper-GUI/assets/146317633/df09bd16-8343-43c3-8aca-8c75c4758f91)
新版本启用whisperX对齐以后转录完就停止了，而且也没有输出任何文件
![无标题](https://github.com/CheshireCC/fatser-whisper-GUI/assets/146317633/a986b27d-0192-475e-833c-cc7d32606e81)

**Comment by CheshireCC** [comment]
哦 好的， 新加入的一行代码没有做测试
my bad

**Comment by wangao1993** [comment]
太感谢了，你的这个工具简直好用到爆炸！

**Comment by CheshireCC** [comment]
已经查明问题所在，但不幸的是，咱现在需要立即更新软件一次，我正在考虑使用其他的安装包制作工具，以期实现增量更新。。。。

**Comment by CheshireCC** [comment]
看起来我们只需要用新的 exe 文件覆盖掉旧的就行了， 文件正在上传 ,晚饭后就能正常更新了

**Comment by wangao1993** [comment]
非常感谢，效率太高了
