### ISSUE TITLE
安装2.6的时候提示由于找不到 python310.dll，无法继续执行代码。重新安装程序可能会解决此问题。

### ISSUE THREAD

**Issue by dadaguai3** [CheshireCC/fatser-whisper-GUI#6]
由于找不到 python310.dll，无法继续执行代码。重新安装程序可能会解决此问题。

**Comment by CheshireCC** [comment]
`0.2.6` 版本是补丁包，需要先安装 `0.2.5` 版本, 之后把解压出来的 `0.2.6` 的 `exe` 文件复制替换掉就可以了

**Comment by dadaguai3** [comment]
非常抱歉，我的问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月2日(星期一) 凌晨1:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CheshireCC/fatser-whisper-GUI] 安装2.6的时候提示由于找不到 python310.dll，无法继续执行代码。重新安装程序可能会解决此问题。 (Issue #6)





 
0.2.6 版本是补丁包，需要先安装 0.2.5 版本, 之后把解压出来的 0.2.6 的 exe 文件复制替换掉就可以了
