### ISSUE TITLE
永远加载模型失败

### ISSUE THREAD

**Issue by BylethC** [CheshireCC/fatser-whisper-GUI#7]
永远加载模型失败，实在不得已前来求助

已经尝试了：
1. 搜索全网关于 fatser-whisper-GUI 的内容，只找到两篇相关的 b 站专栏，但是里面的内容和本处的 readme 几乎是一样的，帮助很小；
2. 自行尝试安装了 CUDA 12.2.2、PyTorch 2、CUDNN 8.9.5.29，设置环境变量，重启计算机等等

软件设置：
![image](https://github.com/CheshireCC/fatser-whisper-GUI/assets/46842736/af2d3ad7-a2f5-48e3-b594-9b63d5ce65b4)

自行在软件根目录创建了 model 文件夹
![image](https://github.com/CheshireCC/fatser-whisper-GUI/assets/46842736/647c1400-cc52-46ee-8ac7-07ca7623e7d0)

fasterwhispergui.log中的内容：
```
==========2023-10-04_16:44:51==========
version: 11070
torchaudio_cuda_version: 11070
_lfilter_core_cpu_loop:torchaudio._lfilter_core_loop
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
```

抱歉，我对深度学习相关的内容没有任何知识储备。但是如果有一个逐步的部署文档，我应该是能像部署其它模型一样使用的

硬件配置是 13900K + 4090，应该不是瓶颈

谢谢！

**Comment by CheshireCC** [comment]
你的问题

不能重命名模型文件，
模型文件应为转换后的格式，非 openAI 的原始格式，
转换后的模型放置到目录下，每个模型一个单独目录，所需要的文件如 config、json，等都一个不能少

![image](https://github.com/CheshireCC/fatser-whisper-GUI/assets/36411617/a66caecd-490d-4d6c-a51e-69a0995cf5d7)

下载地址
```
hugging-face 地址：见首页 
```
```
度盘：
链接：https://pan.baidu.com/s/1nB0TKnA8yUpM3J-rpFS_Hg?pwd=o55k 
提取码：o55k 
--来自百度网盘超级会员V9的分享
```

如果问题解决了，请告知并关闭 issue
如果存在其他问题请继续提问

**Comment by BylethC** [comment]
> 你的问题
> 
> 
> 
> 不能重命名模型文件，
> 
> 模型文件应为转换后的格式，非 openAI 的原始格式，
> 
> 转换后的模型放置到目录下，每个模型一个单独目录，所需要的文件如 config、json，等都一个不能少
> 
> 
> 
> ![image](https://github.com/CheshireCC/fatser-whisper-GUI/assets/36411617/a66caecd-490d-4d6c-a51e-69a0995cf5d7)
> 
> 
> 
> 下载地址
> 
> ```
> 
> hugging-face 地址：见首页 
> 
> ```
> 
> ```
> 
> 度盘：
> 
> 链接：https://pan.baidu.com/s/1nB0TKnA8yUpM3J-rpFS_Hg?pwd=o55k 
> 
> 提取码：o55k 
> 
> --来自百度网盘超级会员V9的分享
> 
> ```
> 
> 
> 
> 如果问题解决了，请告知并关闭 issue
> 
> 如果存在其他问题请继续提问
> 
> 

这回解决了，谢谢！！

**Comment by zhduing** [comment]
![5555](https://github.com/CheshireCC/faster-whisper-GUI/assets/128332851/a1133b59-f8c2-45d6-9e91-e5128b26bc41)

我没有重命名模型文件。永远加载模型失败，实在不得已前来求助。模型是你发的链接网盘下载的

**Comment by weehr** [comment]
遇到了同样的问题，模型就是从这个网盘链接下载的，换用任何一个模型文件夹都是加载失败（整体文件夹直接放在C盘根目录下，不存在路径名称空格或非法字符情况），不知道问题出在哪里。

**Comment by CheshireCC** [comment]
加载失败的时候看看日志
