### ISSUE TITLE
伟大的项目！

### ISSUE THREAD

**Issue by natowi** [CheshireCC/fatser-whisper-GUI#9]
嘿，我只是想感谢你这个伟大的项目！

你能否考虑将 "德国完蛋了!.mp4" 转录截图样本改成争议性较小的内容？这部分视频来自一位极右翼（种族主义）政客的咆哮。
(您可能也不会用特朗普关于中国的演讲中的咆哮部分来推广您的软件吧? ;-) )

无论如何，请继续努力。👍

**Comment by CheshireCC** [comment]
This is a good proposal, and I think we should shelve the dispute first, so I will update the document and delete the controversial content.
In fact, Chinese video websites reprint the video as German language material, and most Chinese, including me, do not know the woman and have no idea whether she advocates "racism" or not.
Anyway, thank you for reminding me.

**Comment by natowi** [comment]
Nothing wrong with using it as learning material :)
